### ISSUE TITLE
how to add codes 

### ISSUE THREAD

**Issue by plato1999** [ahezard/NitroHax3DS#14]
hi in kinda new here but i wanted to use this program  for my pokemon black only issue i cant find it in the cheat list is there any way to manually add the game and codes for it

**Comment by plato1999** [comment]
also any way to add dsi enhanced games

**Comment by Valkristh** [comment]
You need to know the code of the game depending of the region to manually add it, but pkmn black is a dsi enhanced game sooo maybe doesn't work

**Comment by ApacheThunder** [comment]
TWL Carts (aka all DSI Enhanced games and DSi Exclusive games) are not compatible with NitroHax currently. Even if you found cheat codes, the games won't boot due to the ancient cart loading code needing to be updated. The cart loading code from recent builds of GodMode9i may be compatible but will need some adjustments to work with NitroHax.

Also, opening an issue is not an appropriate way for asking for assistance from something. Please do not use this section on Github for requesting codes or help on how to add them. This section is intended for pointing out bugs/problems with NitroHax. (also lack of TWL cart compatibility is a known issue already)
